env: "local"

grpc:
  port: 9095

http:
  port: 8084

jwt_secret: "q9hFqkz+KQx9nM2yC3g2zKcXrKxF3K0M+Zp+uF4ZxN8="

kafka:
  brokers:
    - "localhost:9092"
  consumer_group: "sync-service"
  topics:
    file_events: "file.events"
    sync_notifications: "sync-notifications"
